name: (Used to) catch bugs at the midnight hour

on:
  pull_request:

jobs:
  puck_property_testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: false
          target: wasm32-wasi
      - uses: Swatinem/rust-cache@v1
      - name: tests
        run: ./scripts/proptest.sh --target x86_64-unknown-linux-gnu
      - name: collect results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: http-parsing-witnesses
          path: |
            /home/runner/work/puck/puck/puck/tests/*

  puck_liveview_property_testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: false
          target: wasm32-wasi
      - uses: Swatinem/rust-cache@v1
      - run: ./scripts/proptest_liveview.sh --target x86_64-unknown-linux-gnu
      - name: collect results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: liveview-diffing-witnesses
          path: |
            /home/runner/work/puck/puck/puck_liveview/tests/*
